# inventory.yml
all:
  children:
    basekit:
      hosts:
        localhost:
          ansible_connection: local
      vars:
        domain_name: "base-kit.kratos"

        customer_network:
          gateway: "10.243.76.1"
          cidr: "/23"
          dns_servers: ["10.243.25.50", "10.243.25.53"]

        mgmt_network:
          network: "192.168.2"
          cidr: "/24"
          gateway: "192.168.2.1"
          dns_servers: ["192.168.2.1"]

        ntp:
          server: "192.168.2.100"

      children:
        mgmt_svr:
          hosts:
            mgmt_kvm: 
              ansible_host: 10.243.77.212
              ansible_user: kratos
              ansible_ssh_pass: "kratos"
              ansible_become_pass: "kratos"

              wan_address: "{{ hostvars['mgmt_kvm'].ansible_host }}"
              wan_interface: "eno12409"

              mgmt_address: "192.168.2.6"
              mgmt_interface: "eno12399"

              idrac_address: "192.168.0.4"
              idrac_interface: "ens3f0"

              prov_interface: "eno8303"
                
        vms:
          hosts:
            mcm: 
              ansible_host: 192.168.2.8
              mgmt_interface: "enp1s0"
              ansible_user: "kratos"
              ansible_ssh_pass: "kratos"
              ansible_become_pass: "kratos"
            osms: 
              ansible_host: 192.168.2.9
              mgmt_interface: "enp1s0"
              ansible_user: "kratos"
              ansible_ssh_pass: "kratos"
              ansible_become_pass: "kratos"
            opensense:
              wan_ip: "10.243.77.222"
                
        osdc:
          hosts:
            osdc1: 
              ansible_host: 192.168.0.16
              interface: "enp1s0"
              mac_address: "30:3E:A7:2E:3A:8B"
            osdc2: 
              ansible_host: 192.168.0.17
              interface: "enp1s0"
              mac_address: "30:3E:A7:2E:3A:8C"