version: '3'

vars:
  DATA_DIR: /docker-workspace/data
  INSTALL_DIR: /docker-workspace/config/install
  
  DEPLOYMENT_TYPE: basekit
  DEPLOYMENT_VERSION: 1.0.1
  DEPLOYMENT_PLAN: main.yml

  ONBOARDER_VERSION: 3.5.0-rc7
  ONBOARDER_PLAN: main.yml
  
  NODE_PREP_PLAN: rhel9.yml
  CLUSTER_DEPLOYMENT_PLAN: main.yml

includes:
  deployment:
    taskfile: '{{.DATA_DIR}}/{{.DEPLOYMENT_TYPE}}/{{.DEPLOYMENT_VERSION}}/{{.DEPLOYMENT_PLAN}}'
    vars:
      DATA_DIR: '{{.DATA_DIR}}'
      DEPLOYMENT_TYPE: '{{.DEPLOYMENT_TYPE}}'
      DEPLOYMENT_VERSION: '{{.DEPLOYMENT_VERSION}}'
  
  onboarder:
    taskfile: '{{.DATA_DIR}}/onboarder/{{.ONBOARDER_VERSION}}/{{.ONBOARDER_PLAN}}'
    vars:
      DATA_DIR: '{{.DATA_DIR}}'
      ONBOARDER_VERSION: '{{.ONBOARDER_VERSION}}'
  
  node-prep:
    taskfile: '{{.DATA_DIR}}/node_prep/{{.ONBOARDER_VERSION}}/{{.NODE_PREP_PLAN}}'
    vars:
      DATA_DIR: '{{.DATA_DIR}}'
      ONBOARDER_VERSION: '{{.ONBOARDER_VERSION}}'
  
  cluster-deployment:
    taskfile: '{{.DATA_DIR}}/cluster_deployment/{{.ONBOARDER_VERSION}}/{{.CLUSTER_DEPLOYMENT_PLAN}}'
    vars:
      DATA_DIR: '{{.DATA_DIR}}'
      ONBOARDER_VERSION: '{{.ONBOARDER_VERSION}}'

tasks:
  # Phase 1: Prep
  prep-onboarder-container:
    desc: Prep Onboarder Container
    cmds:
      - task: onboarder:prep-onboarder-container

  run-deployment-setup:
    desc: Run Deployment Setup Tasks
    cmds:
      - task: deployment:deploy-all

  # Phase 2: Deploy Infrastructure (MCM)
  run-node-prep:
    desc: Run Node Preparation Tasks
    cmds:
      - task: node-prep:deploy-all
        vars:
          HOSTS: '{{.HOSTS}}'

  run-onboarder:
    desc: Run Complete Onboarder Deployment
    cmds:
      - task: onboarder:deploy-all

  # Phase 3: Cluster Deployment
  run-cluster-prep:
    desc: Run Cluster Node Preparation
    cmds:
      - task: cluster-deployment:prep-cluster-nodes
        vars:
          HOSTS: '{{.HOSTS}}'

  run-cluster-deploy:
    desc: Deploy Cluster
    cmds:
      - task: cluster-deployment:deploy-clusters
        vars:
          HOSTS: '{{.HOSTS}}'

  # Full Deployment Workflows
  prep:
    desc: Complete environment preparation workflow
    cmds:
      - task: prep-onboarder-container
      - task: run-deployment-setup

  deploy-mcm:
    desc: Complete MCM infrastructure deployment
    vars:
      HOSTS: infrastructure_cluster
    cmds:
      - task: copy-ssh-key
        vars:
          HOSTS: '{{.HOSTS}}'
          ARGS: '-e ssh_pubkey_path=/docker-workspace/config/install/.ssh/rancher_ssh_key.pub'
      - task: run-node-prep
        vars:
          HOSTS: '{{.HOSTS}}'
      - task: run-onboarder

  deploy-prod-osms:
    desc: Complete production OSMS deployment workflow
    vars:
      HOSTS: osms_production
    cmds:
      - task: copy-ssh-key
        vars:
          HOSTS: '{{.HOSTS}}'
          ARGS: '-e ssh_pubkey_path=/docker-workspace/config/install/.ssh/production_ssh_key.pub'
      - task: run-node-prep
        vars:
          HOSTS: '{{.HOSTS}}'
      - task: run-cluster-prep
        vars:
          HOSTS: '{{.HOSTS}}'
      - task: run-cluster-deploy
        vars:
          HOSTS: '{{.HOSTS}}'

  deploy-prod-osdc:
    desc: Complete production OSDC deployment workflow
    vars:
      HOSTS: osdc_production
    cmds:
      - task: copy-ssh-key
        vars:
          HOSTS: '{{.HOSTS}}'
          ARGS: '-e ssh_pubkey_path=/docker-workspace/config/install/.ssh/production_ssh_key.pub'
      - task: run-node-prep
        vars:
          HOSTS: '{{.HOSTS}}'
      - task: run-cluster-prep
        vars:
          HOSTS: '{{.HOSTS}}'
      - task: run-cluster-deploy
        vars:
          HOSTS: '{{.HOSTS}}'

  # Utility Tasks
  copy-ssh-key:
    desc: Copy SSH Key to Node
    vars:
      FILE: '{{.DATA_DIR}}/common/copy_ssh_key.yml'
      KIND: ansible
    cmds:
      - python3 {{.DATA_DIR}}/run_task.py --task-id=copy-ssh-key --hosts={{.HOSTS}} --file={{.FILE}} --kind={{.KIND}} --args="{{.ARGS}}"

  resume:
    desc: Resume deployment from last state
    cmds:
      - python3 {{.DATA_DIR}}/run_task.py --resume

  show-state:
    desc: Show current deployment state
    cmds:
      - |
        STATE_FILE="/docker-workspace/config/install/.cache/state.json"
        if [ -f "$STATE_FILE" ]; then
          cat "$STATE_FILE" | python3 -m json.tool
        else
          echo "No state file found"
        fi

  clean-state:
    desc: Clean deployment state (start fresh)
    prompt: This will delete the state file. Continue?
    cmds:
      - rm -f /docker-workspace/config/install/.cache/state.json
      - echo "State cleared"

  logs:
    desc: List recent task logs
    cmds:
      - ls -lt /docker-workspace/config/install/.cache/logs/ | head -10

  tail-log:
    desc: Tail a specific task log
    requires:
      vars: [TASK_ID]
    cmds:
      - tail -f /docker-workspace/config/install/.cache/logs/{{.TASK_ID}}.log