version: '3'

vars:
  ENV: afcgi_skcp_bottom
  DATA_DIR: /docker-workspace/data
  ENV_DIR: /docker-workspace/config/{{.ENV}}
  TASK_FILES_DIR: '{{.DATA_DIR}}/task_files'
  TASK_DIR: '{{.DATA_DIR}}/tasks'

  DEPLOYMENT_TYPE: basekit
  DEPLOYMENT_VERSION: 1.0.1

  ONBOARDER_VERSION: 3.5.0-rc7
  OS: Rhel9

includes:
  deployment:
    taskfile: '{{.TASK_FILES_DIR}}/{{.DEPLOYMENT_TYPE}}/{{.DEPLOYMENT_VERSION}}/default.yml'
    vars:
      ENV: '{{.ENV}}'
      DATA_DIR: '{{.DATA_DIR}}'
      ONBOARDER_VERSION: '{{.ONBOARDER_VERSION}}'
  onboarder:
    taskfile: '{{.TASK_FILES_DIR}}/onboarder/{{.ONBOARDER_VERSION}}/default.yml'
    vars:
      ENV: '{{.ENV}}'
      DATA_DIR: '{{.DATA_DIR}}'
      ONBOARDER_VERSION: '{{.ONBOARDER_VERSION}}'
  node_prep:
    taskfile: '{{.TASK_FILES_DIR}}/node_prep/{{.ONBOARDER_VERSION}}/{{.OS}}/default.yml'
    vars:
      ENV: '{{.ENV}}'
      DATA_DIR: '{{.DATA_DIR}}'
      ONBOARDER_VERSION: '{{.ONBOARDER_VERSION}}'
  cluster_deployment:
    taskfile: '{{.TASK_FILES_DIR}}/cluster_deployment/{{.ONBOARDER_VERSION}}/default.yml'
    vars:
      ENV: '{{.ENV}}'
      DATA_DIR: '{{.DATA_DIR}}'
      ONBOARDER_VERSION: '{{.ONBOARDER_VERSION}}'

tasks:
  # Phase 1: Common Setup Tasks
  prep-onboarder-container:
    desc: Prep Onboarder Container
    cmds:
      - task: onboarder:prep-onboarder-container

  # Phase 2: Deployment Setup From Deployment Version File
  run-deployment-setup:
    desc: Run Deployment Setup Tasks
    cmds:
      - task: deployment:deploy-all

  # Phase 3: Cluster node prep
  node_prep:
    desc: Run Cluster Node Preparation Tasks
    cmds:
      - task: node_prep:deploy-all

  # Phase 4: Run Onboarder
  run-onboarder:
    desc: Run Complete Onboarder Deployment
    cmds:
      - task: onboarder:deploy-all

  # Phase 5: Cluster Deployment
  deploy-clusters:
    desc: Deploy OpenSpace Clusters
    cmds:
      - task: cluster_deployment:deploy-all

  # Phase #: Post Install Tasks
  write-version-manifest:
    desc: Write Version Manifest
    cmds:
      - |
        MANIFEST_FILE="{{.ENV_DIR}}/version_manifest.yml"
        echo "environment: {{.ENV}}" > $MANIFEST_FILE
        echo "basekit_version: {{.BASEKIT_VERSION}}" >> $MANIFEST_FILE
        echo "onboarder_version: {{.ONBOARDER_VERSION}}" >> $MANIFEST_FILE
        echo "node_prep_version: {{.NODE_PREP_VERSION}}" >> $MANIFEST_FILE
        echo "cluster_deployment_version: {{.CLUSTER_DEPLOYMENT_VERSION}}" >> $MANIFEST_FILE
        echo "Version manifest written to $MANIFEST_FILE"

  # Full Deployment Workflow
  deploy:
    desc: Complete environment deployment workflow
    summary: |
      Runs the full deployment workflow for the {{.ENV}} environment using
      pinned, versioned Taskfiles so the install can be reproduced later.

      Component versions:
        - Basekit deployment:         {{.BASEKIT_VERSION}}
        - Onboarder:                  {{.ONBOARDER_VERSION}}
        - Node preparation:           {{.NODE_PREP_VERSION}}
        - Cluster deployment:         {{.CLUSTER_DEPLOYMENT_VERSION}}

      Execution phases:
        1. Prep onboarder container
           - Task: prep-onboarder-container (delegates to onboarder:prep-onboarder-container)

        2. Run basekit / deployment setup
           - Task: run-deployment-setup (delegates to deployment:deploy-all)

        3. Run cluster node preparation
           - Task: node_prep (delegates to node_prep:deploy-all)

        4. Run complete onboarder deployment
           - Task: run-onboarder (delegates to onboarder:deploy-all)

        5. Deploy OpenSpace clusters
           - Task: deploy-clusters (delegates to cluster_deployment:deploy-all)
    cmds:
      - task: prep-onboarder-container
      - task: run-deployment-setup
      - task: node_prep
      - task: run-onboarder
      - task: deploy-clusters
      - task: write-version-manifest


  resume:
    desc: Resume deployment from last state
    cmds:
      - python3 {{.DATA_DIR}}/run_task.py --env={{.ENV}} --resume

  # Utility Tasks
  show-state:
    desc: Show current deployment state
    cmds:
      - |
        STATE_FILE="config/{{.ENV}}/.cache/state.json"
        if [ -f "$STATE_FILE" ]; then
          cat "$STATE_FILE" | python3 -m json.tool
        else
          echo "No state file found for {{.ENV}}"
        fi

  clean-state:
    desc: Clean deployment state (start fresh)
    prompt: This will delete the state file for {{.ENV}}. Continue?
    cmds:
      - rm -f config/{{.ENV}}/.cache/state.json
      - echo "State cleared for {{.ENV}}"

  logs:
    desc: List recent task logs
    cmds:
      - ls -lt config/{{.ENV}}/.cache/logs/ | head -10

  tail-log:
    desc: Tail a specific task log
    requires:
      vars: [TASK_ID]
    cmds:
      - tail -f config/{{.ENV}}/.cache/logs/{{.TASK_ID}}.log