# inventory.yml
all:
  vars:
    core:
      profile: "basekit"
      hardened: true
      onboarder: "onboarder-full.3.6.0.tar.gz"
    dns:
      servers: ["10.0.0.52", "10.0.0.53"]
      domain_name: "example.local"
    ntp:
      servers: ["10.0.0.52", "10.0.0.53"]

  children:
    mcms:
      vars:
        cluster_name: "mcm-cluster"
      hosts:
        mcm1: 
          ansible_host: 10.0.0.110
        mcm2: 
          ansible_host: 10.0.0.111
        mcm3: 
          ansible_host: 10.0.0.112

    osms:
      vars:
        cluster_name: "osms-cluster"
      hosts:
        osms1: 
          ansible_host: 10.0.0.113
        osms2: 
          ansible_host: 10.0.0.114
        osms3: 
          ansible_host: 10.0.0.115

    osdc:
      vars:
        cluster_name: "osdc-cluster"
      hosts:
        osdc1: 
          ansible_host: 10.0.0.116
        osdc2: 
          ansible_host: 10.0.0.117
        osdc3: 
          ansible_host: 10.0.0.118

    # -------------------------
    # Basekit Specific Hosts
    # -------------------------
    basekit:
      vars:
        profile: "basekit-default"
        basekit_enable_monitoring: true
        basekit_packages:
          - curl
          - jq
          - htop
      hosts:
        mgmt-svr:
          ansible_host: 10.0.0.6
          profile: "basekit-mgmt-server"
